# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 天翔的博客
subtitle: ''
description: 明日尚未到来，希望凝于心上
keywords: 天翔, 博客
author: '天翔TNXG'
language: 'zh-CN'
timezone:

#ImagesUrl
images:
  enable: true
  markdowm: true
  domain: https://assets.tnxg.whitenuo.cn
  #domain: https://assets.prts.top

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://tnxg.loyunet.cn/
permalink: /p/:hash.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - 'config.yaml'
  - 'blog-cgi/index.html'

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

highlight:
  enable: false

prismjs:
  enable: true
  preprocess: true
  line_number: true

index_generator:
  path: ''
  per_page: 15
  order_by: -date

default_category: uncategorized

meta_generator: true

date_format: YYYY-MM-DD
time_format: HH:mm:ss

ignore_hidden: false

updated_option: 'mtime'

per_page: 10
pagination_dir: page

theme: yun

feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 0


encrypt:
  abstract: 有东西被加密了, 请输入密码查看.
  message: 您好, 这里需要密码.
  tags:
  - {name: tagName, password: 密码A}
  - {name: tagName, password: 密码B}
  wrong_pass_message: 抱歉, 这个密码看着不太对, 请再试试.
  wrong_hash_message: 抱歉, 这个文章不能被校验, 不过您还是能看看解密后的内容.


hexo_seo_autopush:
  cron: 0 0,6,12,18,21 * * *
  baidu:
    enable: true
    date: created
    count: 50
  bing:
    enable: true
    date: created
    count: 50
  google:
    enable: true
    date: created
    count: 50

sitemap:
  path: 
    - sitemap.xml
  rel: true
  tags: true
  categories: true