global:
  # 导航栏左侧的标题，为空则按 hexo config 中 `title` 显示
  nav_title: "天翔TNXGの空间站"
  # 用于浏览器标签的图标
  favicon: "/favicon.png"
  # 用于苹果设备的图标
  apple_touch_icon: "/favicon.png"
  # 强制所有链接升级为 HTTPS（适用于图片等资源出现 HTTP 混入报错）
  force_https: true
  # 浏览器标签页中的标题分隔符，效果： 文章名 - 站点名
  title_join_string: " | "
  # 每次生成页面后，检测主题是否为最新版本
  version_check: true
  # 网页访问统计
  web_analytics:
    google: "G-RLK9KD8ZT6"
    woyaolav6:
      id: "JuuJr9Xtk01ykQVU"
      ck: "JuuJr9Xtk01ykQVU"
  # 在页面底部加入 Copyright
  copyright:
    enable: true
    from_year: 2019
    to_year: 2023
    name: "天翔TNXG"
  ## 哀悼模式，网页黑白
  # memorial:
  #    enable: false
  #    date: "7-8"
  comment: true

  font:
    # 页面字体
    family: "\"HarmonyOS_Regular\""
    # 字体 CSS 文件，选填。注意，字体 CSS 文件不是字体文件，而是像 Google Fonts 一样声明字体的文件。
    css: "/assets/css/font.css"

# 默认说说页
talk:
  enable: false

# 搜索
search:
  enable: true
  # 搜索索引文件的路径，可以是相对路径或外站的绝对路径
  path: /search.json
  # 搜索的范围
  field: all

beian:
  enable: false

# 自定义
custom:
  js:
    - "/assets/js/message.js"
    - "/assets/js/master.js"

  css:
    - "/assets/css/master.css"
    - "/assets/css/shiki.css"
    - "/assets/css/float.css"
    - "https://npm.elemecdn.com/remixicon@2.5.0/fonts/remixicon.css"

index:
  # 名称
  name: "天翔TNXGの空间站"
  slogan: '<p><span id="tnxg_hitokoto"></span></p><p><span id="tnxg_notice">Loading...</span></p><p>您在阅读博文时视为同意使用条款</p>'
  # 文章通过 `sticky` 排序
  post_sticky:
    enable: true
    text: "[TOP]"

  # 文章卡片是否显示相关信息（时间、分类、标签）
  post_meta:
    date: true
    category: true
    tag: true
  # 自动截取文章摘要，前 200 字符
  auto_excerpt:
    enable: true
navbar:
  menu:
    首页: "/"
    存档: "/archives/"
    说说: "/talks/"
    友链: "/links/"
    友圈: "/friendcircle/"
    开往: "https://travellings.link/"
    条款: "/policy/"
    更多: "/more/"
    关于: "/about/"

post:
  readingProgess:
    enable: true

  meta:
    author: true
    date: true
    date_format: "YYYY-MM-DD HH:mm"
  wordcount:
    enable: true
    format: "共 {} 字"
  min2read:
    enable: false
    format: "预计 {} 分钟"
    words: 100

  # 评论插件
  comment: true

  code:
    highlight: false

  fancybox:
    enable: true

  # mermaid:
  #   enable: true
  #   specific: false
  #   # See: http://mermaid-js.github.io/mermaid/
  #   options: { theme: "default" }

  # 版权声明，会显示在每篇文章的结尾
  copyright:
    enable: true
    authorURL: /
    content: '本博客所有文章除特别声明外，均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh" rel="nofollow noopener">CC BY-NC-SA 4.0 协议</a> ，转载请注明出处，非常感谢。'
    cc: true

  # 文末打赏
  donate:
    enable: true
    # 打赏文字
    text: "喜欢这篇文章？为什么不考虑打赏一下作者呢？"
    # 方式
    way:
      赞赏: "/donate/"

comment:
  type: artalk
  artalk:
    envid: "https://artalk.prts.top"
  # type: twikoo
  # twikoo:
  #   envid: "https://api-twikoo.prts.top"
  #   isVercel: true

category:
  enable: true

archive:
  title: 归档

tag:
  enable: true
  subtitle:
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px
    start_color: "#acb3c2"
    end_color: "#454d5d"

links:
  enable: true
  json_links:
    enable: true
    item_links: "https://blog.tnxg.top/assets/data/links.json"

page404:
  enable: true

static_prefix:
  twikoo: "https://assets.tnxg.whitenuo.cn/static/twikoo/1.6.8/"
  artalk: "https://cdn.staticfile.org/artalk/2.4.4/"

lazyload:
  enable: true
  onlypost: false
  loadingImage: "https://assets.tnxg.whitenuo.cn/images/face/Q_Matikanetannhauser_dance.gif?fmt=webp"

qexo_time:
  enable: false
