name: ClientWorker
catch_rules:
  - rule: _
    transform_rules:
      - search: \#.+
        searchin: url
        replace: ""
      - search: _
        action: fetch
        fetch:
          engine: fetch
      - search: (^4|^5)
        searchin: status
        action: return
        return:
          body: The GateWay is down!This Page is provided by ClientWorker!
          status: 503

      - search: ^https:\/\/(cdn|fastly|test1|gcore)\.jsdelivr\.net\/npm\/
        replace:
          - https://s-cd-1806-tnxg-oss-cdn.oss.dogecdn.com/npm/
          - https://cdn.bilicdn.tk/npm/
          - https://unpkg.com/
          - https://npm.elemecdn.com/
          - https://cdn.jsdelivr.net/npm/
          - https://jsd.8b9.cn/npm/
          - https://jsd.onmicrosoft.cn/npm/
          - https://unpkg.onmicrosoft.cn/
          - https://npm.sourcegcdn.com/
          - https://cdn1.tianli0.top/npm/

      - search: ^https:\/\/s-cd-1806-tnxg-oss-cdn\.oss\.dogecdn\.com\/npm\/
        replace:
          - https://s-cd-1806-tnxg-oss-cdn.oss.dogecdn.com/npm/
          - https://cdn.bilicdn.tk/npm/
          - https://unpkg.com/
          - https://npm.elemecdn.com/
          - https://cdn.jsdelivr.net/npm/
          - https://jsd.8b9.cn/npm/
          - https://jsd.onmicrosoft.cn/npm/
          - https://unpkg.onmicrosoft.cn/
          - https://npm.sourcegcdn.com/
          - https://cdn1.tianli0.top/npm/

      - search: ^https:\/\/unpkg\.com\/
        replace:
          - https://s-cd-1806-tnxg-oss-cdn.oss.dogecdn.com/npm/
          - https://cdn.bilicdn.tk/npm/
          - https://unpkg.com/
          - https://npm.elemecdn.com/
          - https://cdn.jsdelivr.net/npm/
          - https://jsd.8b9.cn/npm/
          - https://jsd.onmicrosoft.cn/npm/
          - https://unpkg.onmicrosoft.cn/
          - https://npm.sourcegcdn.com/
          - https://cdn1.tianli0.top/npm/

      - search: ^https:\/\/(cdn|fastly|test1|gcore)\.jsdelivr\.net\/gh\/
        replace:
          - https://s-cd-1806-tnxg-oss-cdn.oss.dogecdn.com/gh/
          - https://cdn.bilicdn.tk/gh/
          - https://gcore.jsdelivr.net/gh/
          - https://jsd.8b9.cn/gh/
          - https://jsd.onmicrosoft.cn/gh/
          - https://cdn1.tianli0.top/gh/

      - search: ^https:\/\/s-cd-1806-tnxg-oss-cdn\.oss\.dogecdn\.com\/gh\/
        replace:
          - https://s-cd-1806-tnxg-oss-cdn.oss.dogecdn.com/gh/
          - https://cdn.bilicdn.tk/gh/
          - https://gcore.jsdelivr.net/gh/
          - https://jsd.8b9.cn/gh/
          - https://jsd.onmicrosoft.cn/gh/
          - https://cdn1.tianli0.top/gh/

      - search: _
        replace:
          - _ #保留原始请求
          - s-cd-1806-tnxg-oss-cdn.oss.dogecdn.com/npm/tnxg-blog@latest
          - cdn.bilicdn.tk/npm/tnxg-blog@latest
          - unpkg.com/tnxg-blog@latest #NPM托管
          - cdn-api.vercel.app

      - search: \.html$
        header:
          Content-Type: text/html;charset=UTF-8 #修复标头

      - search: _
        action: fetch
        fetch:
          status: 200
          engine: classic
          preflight: false
          timeout: 5000
