name: TNXGClientWorker
catch_rules:
  - rule: _
    transform_rules:
      - search: tnxg.loyunet.cn # 匹配tnxg.loyunet.cn，跳为/blog.tnxg.top/
        action: redirect
        redirect:
          to: blog.tnxg.top
          status: 301
      - search: _
        replace:
          - _
          - gcore.blog.tnxg.top
          - vercel.blog.tnxg.top
        action: fetch
        fetch:
          status: .*
          engine: parallel
          preflight: false # false
          timeout: 30000
          delay: 4000
      - search: \/([^\/.]+)$ # 匹配/path，跳为/path/
        action: redirect
        redirect:
          to: /$1/
          status: 301

  - rule: ((cdn|test1|quantil|fastly|gcore)\.jsdelivr\.net\/npm)|(unpkg\.com)|(npm\.elemecdn\.com) # 并发npm资源
    transform_rules:
      - search: _
        replace:
          - npm.elemecdn.com
          - assets.tnxg.whitenuo.cn/proxy/npm
          - npm.onmicrosoft.cn
          - _
        action: fetch
        fetch:
          status: 200
          engine: parallel
          preflight: false
          timeout: 3000
          cache:
            expire: 1000*60*60*12
            delay: 300

  - rule: (cdn|test1|quantil|fastly|gcore)\.jsdelivr\.net\/gh # 并发github资源
    transform_rules:
      - search: _
        replace:
          - assets.tnxg.whitenuo.cn/proxy/gh
          - jsd.onmicrosoft.cn/gh
          - _
        action: fetch
        fetch:
          status: 200
          engine: parallel
          preflight: false
          timeout: 3000
          cache:
            expire: 1000*60*60*12
            delay: 300

  - rule: ^(http|https)\:\/\/(i0|i1|i2|i3|s1|s2|s3)\.hdslb\.com # 匹配B站资源链接
    transform_rules:
      - search: _ # 多cdn并发
        replace:
          - https://s1.hdslb.com
          - https://s2.hdslb.com
          - https://s3.hdslb.com
        header:
          referrer: no-referrer # 更改引用策略
        action: fetch
        fetch:
          engine: parallel
          status: 200
          preflight: false
          timeout: 30000
          delay: 4000

  - rule: (?<=^(http|https)\:\/\/assets\.tnxg\.whitenuo.cn/(.*))\.jpg$
    transform_rules:
      - search: image\/webp
        searchin: header
        searchkey: Accept
        replace: .jpg?fmt=webp
        replacein: url
        replacekey: .jpg
        action: fetch
        fetch:
          expire: 1000*60*60*24*365 #CDN默认缓存一年
  - rule: (?<=^(http|https)\:\/\/assets\.tnxg\.whitenuo.cn/(.*))\.png$
    transform_rules:
      - search: image\/webp
        searchin: header
        searchkey: Accept
        replace: .png?fmt=webp
        replacein: url
        replacekey: .png
        action: fetch
        fetch:
          expire: 1000*60*60*24*365 #CDN默认缓存一年
  - rule: (?<=^(http|https)\:\/\/assets\.tnxg\.whitenuo.cn/(.*))\.jpeg$
    transform_rules:
      - search: image\/webp
        searchin: header
        searchkey: Accept
        replace: .jpeg?fmt=webp
        replacein: url
        replacekey: .jpeg
        action: fetch
        fetch:
          expire: 1000*60*60*24*365 #CDN默认缓存一年
  - rule: (?<=^(http|https)\:\/\/assets\.tnxg\.whitenuo.cn/(.*))\.gif$
    transform_rules:
      - search: image\/webp
        searchin: header
        searchkey: Accept
        replace: .gif?fmt=webp
        replacein: url
        replacekey: .gif
        action: fetch
        fetch:
          expire: 1000*60*60*24*365 #CDN默认缓存一年

  - rule: (http|https)\:\/\/(.*)\/prism\/(.*)\/themes\/prism\-prism\-vsc\-dark\-plus.min\.css$ # 匹配xx/prism/xxx/themes/prism-prism-vsc-dark-plus.min.css
    transform_rules:
      - search: (http|https)\:\/\/(.*)\/prism\/(.*)\/themes\/prism\-prism\-vsc\-dark\-plus.min\.css$ # 寻找 xx/prism/xxx/themes/prism-prism-vsc-dark-plus.min.css的内容
        replace: https://cdn.staticfile.org/prism-themes/1.9.0/prism-vsc-dark-plus.css
        action: fetch
        fetch:
          engine: fetch
          status: 200
          preflight: false
          expire: 1000*60*60*24
